//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierAPI.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierOAuthData
    {
        public int Id { get; set; }
        public int CourierId { get; set; }
        public string JWToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpires { get; set; }
        public Nullable<bool> RefreshTokenIsActive { get; set; }
        public string RefreshTokenIp { get; set; }
    
        public virtual Courier Courier { get; set; }
    }
}
