//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierAPI.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierShiftHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourierShiftHistory()
        {
            this.IncomingOrderHistories = new HashSet<IncomingOrderHistory>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int CourierShiftId { get; set; }
        public bool IsStarted { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public bool IsEnded { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool IsPaused { get; set; }
        public Nullable<int> PauseReasonId { get; set; }
        public Nullable<System.DateTime> PauseTime { get; set; }
        public string PauseDescription { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CourierShift CourierShift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingOrderHistory> IncomingOrderHistories { get; set; }
        public virtual ShiftPauseReason ShiftPauseReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
