//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using CourierAPI.Infrastructure.Database;

namespace CourierAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HDEntities : DbContext
    {
        public HDEntities()
            : base("name=HDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyInSocialNetwork> CompanyInSocialNetworks { get; set; }
        public virtual DbSet<CompanyPhone> CompanyPhones { get; set; }
        public virtual DbSet<CompanySchedule> CompanySchedules { get; set; }
        public virtual DbSet<CourierFile> CourierFiles { get; set; }
        public virtual DbSet<CourierLockReason> CourierLockReasons { get; set; }
        public virtual DbSet<CourierMovementMethod> CourierMovementMethods { get; set; }
        public virtual DbSet<CourierOAuthData> CourierOAuthDatas { get; set; }
        public virtual DbSet<CourierPenalty> CourierPenalties { get; set; }
        public virtual DbSet<Courier> Couriers { get; set; }
        public virtual DbSet<CourierShift> CourierShifts { get; set; }
        public virtual DbSet<CourierShiftHistory> CourierShiftHistories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EmployeeLockReason> EmployeeLockReasons { get; set; }
        public virtual DbSet<EmployeePosition> EmployeePositions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<IncomingOrderHistory> IncomingOrderHistories { get; set; }
        public virtual DbSet<IncomingOrderStatu> IncomingOrderStatus { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<OperationStatus> OperationStatuses { get; set; }
        public virtual DbSet<OrderEmailSendLog> OrderEmailSendLogs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatusCode> OrderStatusCodes { get; set; }
        public virtual DbSet<PaymentSystem> PaymentSystems { get; set; }
        public virtual DbSet<PenaltyCategory> PenaltyCategories { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RestaurantCategory> RestaurantCategories { get; set; }
        public virtual DbSet<RestaurantInCategory> RestaurantInCategories { get; set; }
        public virtual DbSet<RestaurantMenu> RestaurantMenus { get; set; }
        public virtual DbSet<RestaurantMenuItem_Order> RestaurantMenuItem_Order { get; set; }
        public virtual DbSet<RestaurantMenuItem> RestaurantMenuItems { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<ShiftPauseReason> ShiftPauseReasons { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SMSHandler> SMSHandlers { get; set; }
        public virtual DbSet<SMSSendLog> SMSSendLogs { get; set; }
        public virtual DbSet<SMSSetting> SMSSettings { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetworks { get; set; }
        public virtual DbSet<StoreCategory> StoreCategories { get; set; }
        public virtual DbSet<StoreProduct_Order> StoreProduct_Order { get; set; }
        public virtual DbSet<StoreProductInCategory> StoreProductInCategories { get; set; }
        public virtual DbSet<StoreProduct> StoreProducts { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreSubCategory> StoreSubCategories { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehiclesGallery> VehiclesGalleries { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
    }
}
