//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierAPI.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string MobilePhone { get; set; }
        public int GenderId { get; set; }
        public int PositionId { get; set; }
        public string Description { get; set; }
        public Nullable<int> LockedReasonId { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual EmployeeLockReason EmployeeLockReason { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
