//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierAPI.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingOrder
    {
        public int CourierShiftHistoryId { get; set; }
        public int OrderId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual CourierShiftHistory CourierShiftHistory { get; set; }
        public virtual IncomingOrderStatus IncomingOrderStatus { get; set; }
        public virtual Order Order { get; set; }
    }
}
