//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierAPI.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.IncomingOrderHistories = new HashSet<IncomingOrderHistory>();
            this.RestaurantMenuItem_Order = new HashSet<RestaurantMenuItem_Order>();
            this.StoreProduct_Order = new HashSet<StoreProduct_Order>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CourierId { get; set; }
        public int OrderStatusCodeId { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> DeliveryRegionId { get; set; }
        public string DeliveryCustomerNote { get; set; }
        public Nullable<System.DateTime> DeliveryStartedAt { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
        public Nullable<int> CustomerRate { get; set; }
        public string CustomerRateNote { get; set; }
        public string EmployeeNote { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<int> CustomerGenderId { get; set; }
        public Nullable<int> SupplierOrderPreparationTime { get; set; }
        public Nullable<System.DateTime> SupplierCallAt { get; set; }
        public string SupplierCallBy { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> CourierShiftHistoryId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Courier Courier { get; set; }
        public virtual CourierShiftHistory CourierShiftHistory { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingOrderHistory> IncomingOrderHistories { get; set; }
        public virtual OrderStatusCode OrderStatusCode { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantMenuItem_Order> RestaurantMenuItem_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreProduct_Order> StoreProduct_Order { get; set; }
    }
}
