//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierAPI.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSendLog
    {
        public int Id { get; set; }
        public int SMSSettingId { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
        public int Status { get; set; }
        public Nullable<int> HandlerId { get; set; }
        public string SenderIp { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SMSHandler SMSHandler { get; set; }
        public virtual SMSSetting SMSSetting { get; set; }
    }
}
